#
# Copyright 2023 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

[versions]

compileSdk = "36"
targetSdk = "34"
agp = "8.13.2"

# AndroidX
activity = "1.12.2"
appCompat = "1.7.1"
browser = "1.9.0"
compose = "2025.12.01"
concurrent = "1.3.0"
constraintLayout = "2.2.1"
core = "1.17.0"
drawerLayout = "1.2.0"
exifInterface = "1.4.2"
fragment = "1.8.9"
lifecycle = "2.10.0"
multidex = "2.0.1"
navigation = "2.9.6"
paging = "3.3.6"
preference = "1.2.1"
recyclerView = "1.4.0"
room = "2.8.4"
watchface = "1.2.1"
wear = "1.3.0"
wearPhoneInteractions = "1.1.0"
wearRemoteInteractions = "1.1.0"
workManager = "2.11.0"

# Firebase
firebaseAnalytics = "23.0.0"
firebaseCrashlytics = "20.0.3"
firebaseCrashlyticsGradle = "3.0.6"
firebasePerf = "22.0.4"
firebasePerfPlugin = "2.0.2"

# Google Play services
googleServices = "4.4.4"
playServicesWearable = "19.0.0"
wearable = "2.9.0"

# Jetbrains
coroutines = "1.10.2"
dokka = "1.9.0"
kotlin = "2.3.0"
ksp = "2.3.4"

# Other
coil = "3.3.0"
material = "1.13.0"
okhttp = "5.3.2"
okhttpCoroutines = "1.0"
retrofit = "3.0.0"
subsampling = "3.10.0"
tasker = "0.4.10"

[libraries]

agp = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }

# Use the minimum value needed for muzei-api to avoid forcing apps to upgrade
#noinspection GradleDependency
api-core = { group = "androidx.core", name = "core", version.prefer = "1.1.0" }
#noinspection SimilarGradleDependency
api-exifinterface = { group = "androidx.exifinterface", name = "exifinterface", version.ref = "exifInterface" }

# AndroidX
activity = { group = "androidx.activity", name = "activity-compose", version.ref = "activity" }
appCompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appCompat" }
browser = { group = "androidx.browser", name = "browser", version.ref = "browser" }
compose-animation-graphics = { group = "androidx.compose.animation", name = "animation-graphics" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose" }
compose-icons = { group = "androidx.compose.material", name = "material-icons-extended" }
compose-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-ui-tooling-runtime = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
concurrent = { group = "androidx.concurrent", name = "concurrent-futures-ktx", version.ref = "concurrent" }
constraintLayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintLayout" }
core = { group = "androidx.core", name = "core-ktx", version.ref = "core" }
drawerLayout = { group = "androidx.drawerlayout", name = "drawerlayout", version.ref = "drawerLayout" }
#noinspection SimilarGradleDependency
exifInterface = { group = "androidx.exifinterface", name = "exifinterface", version.ref = "exifInterface" }
fragment = { group = "androidx.fragment", name = "fragment-compose", version.ref = "fragment" }
lifecycle-common = { group = "androidx.lifecycle", name = "lifecycle-common-java8", version.ref = "lifecycle" }
lifecycle-livedata = { group = "androidx.lifecycle", name = "lifecycle-livedata", version.ref = "lifecycle" }
lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }
lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
multidex = { group = "androidx.multidex", name = "multidex", version.ref = "multidex" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment-compose", version.ref = "navigation" }
navigation-safeargs = { group = "androidx.navigation", name = "navigation-safe-args-gradle-plugin", version.ref = "navigation" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation" }
paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "paging" }
paging-runtime = { group = "androidx.paging", name = "paging-runtime", version.ref = "paging" }
preference = { group = "androidx.preference", name = "preference-ktx", version.ref = "preference" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-paging = { group = "androidx.room", name = "room-paging", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
recyclerView = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerView" }
wear-core = { group = "androidx.wear", name = "wear", version.ref = "wear" }
wear-phone = { group = "androidx.wear", name = "wear-phone-interactions", version.ref = "wearPhoneInteractions" }
wear-remote = { group = "androidx.wear", name = "wear-remote-interactions", version.ref = "wearRemoteInteractions" }
watchface-core = { group = "androidx.wear.watchface", name = "watchface", version.ref = "watchface" }
watchface-complications-data = { group = "androidx.wear.watchface", name = "watchface-complications-data-source-ktx", version.ref = "watchface" }
watchface-complications-rendering = { group = "androidx.wear.watchface", name = "watchface-complications-rendering", version.ref = "watchface" }
workManager = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workManager" }

# Firebase
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics", version.ref = "firebaseAnalytics" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics", version.ref = "firebaseCrashlytics" }
firebase-crashlytics-gradle = { group = "com.google.firebase", name = "firebase-crashlytics-gradle", version.ref = "firebaseCrashlyticsGradle" }
firebase-perf = { group = "com.google.firebase", name = "firebase-perf", version.ref = "firebasePerf" }
firebase-perf-plugin = { group = "com.google.firebase", name = "perf-plugin", version.ref = "firebasePerfPlugin" }

# Google Play services
googleservices = { group = "com.google.gms", name = "google-services", version.ref = "googleServices" }
wearable-playservices = { group = "com.google.android.gms", name = "play-services-wearable", version.ref = "playServicesWearable" }
wearable-compile = { group = "com.google.android.wearable", name = "wearable", version.ref = "wearable" }
wearable-support = { group = "com.google.android.support", name = "wearable", version.ref = "wearable" }

# Jetbrains
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-playservices = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-play-services", version.ref = "coroutines" }
dokka = { group = "org.jetbrains.dokka", name = "dokka-gradle-plugin", version.ref = "dokka" }
kotlin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

# Other
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coil-runtime = { group = "io.coil-kt.coil3", name = "coil", version.ref = "coil" }
coil-okhttp = { group = "io.coil-kt.coil3", name = "coil-network-okhttp", version.ref = "coil" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
okhttp-core = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-coroutines = { group = "ru.gildor.coroutines", name = "kotlin-coroutines-okhttp", version.ref = "okhttpCoroutines" }
retrofit-core = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit" }
subsampling = { group = "com.davemorrissey.labs", name = "subsampling-scale-image-view-androidx", version.ref = "subsampling" }
tasker = { group = "com.joaomgcd", name = "taskerpluginlibrary", version.ref = "tasker" }

[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }