#
# Copyright 2023 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

[versions]

compileSdk = "33"
targetSdk = "33"
agp = "7.4.2"

# AndroidX
activity = "1.7.2"
appCompat = "1.7.0-alpha02"
browser = "1.5.0"
constraintLayout = "2.1.4"
core = "1.10.1"
drawerLayout = "1.2.0"
exifInterface = "1.3.6"
fragment = "1.6.0"
lifecycle = "2.6.1"
multidex = "2.0.1"
navigation = "2.7.0-beta01"
paging = "3.2.0-beta01"
preference = "1.2.0"
recyclerView = "1.3.1-rc01"
room = "2.6.0-alpha01"
swipeRefreshLayout = "1.1.0"
viewPager2 = "1.1.0-beta02"
watchface = "1.1.1"
wear = "1.2.0"
workManager = "2.9.0-alpha01"

# Firebase
firebaseAnalytics = "21.3.0"
firebaseCrashlytics = "18.3.7"
firebaseCrashlyticsGradle = "2.9.6"
firebasePerf = "20.3.3"
firebasePerfPlugin = "1.4.2"

# Google Play services
googleServices = "4.3.15"
playServicesWearable = "18.0.0"
wearable = "2.8.1"

# Jetbrains
coroutines = "1.6.4"
dokka = "1.6.0"
kotlin = "1.8.20"
ksp = "1.8.20-1.0.11"

# Other
coil = "1.3.2"
material = "1.9.0"
#noinspection GradleDependency
okhttp = "3.12.12"
okhttpCoroutines = "1.0"
retrofit = "2.9.0"
subsampling = "3.10.0"
tasker = "0.4.1"

[libraries]

agp = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }

# Use the minimum value needed for muzei-api to avoid forcing apps to upgrade
#noinspection GradleDependency
api-core = { group = "androidx.core", name = "core", version.prefer = "1.1.0" }
api-exifinterface = { group = "androidx.exifinterface", name = "exifinterface", version.ref = "exifInterface" }

# AndroidX
activity = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity" }
appCompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appCompat" }
browser = { group = "androidx.browser", name = "browser", version.ref = "browser" }
constraintLayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintLayout" }
core = { group = "androidx.core", name = "core-ktx", version.ref = "core" }
drawerLayout = { group = "androidx.drawerlayout", name = "drawerlayout", version.ref = "drawerLayout" }
exifInterface = { group = "androidx.exifinterface", name = "exifinterface", version.ref = "exifInterface" }
fragment = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragment" }
lifecycle-common = { group = "androidx.lifecycle", name = "lifecycle-common-java8", version.ref = "lifecycle" }
lifecycle-livedata = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycle" }
lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
multidex = { group = "androidx.multidex", name = "multidex", version.ref = "multidex" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation" }
navigation-safeargs = { group = "androidx.navigation", name = "navigation-safe-args-gradle-plugin", version.ref = "navigation" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation" }
paging = { group = "androidx.paging", name = "paging-runtime-ktx", version.ref = "paging" }
preference = { group = "androidx.preference", name = "preference-ktx", version.ref = "preference" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-paging = { group = "androidx.room", name = "room-paging", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
recyclerView = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerView" }
swipeRefreshLayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swipeRefreshLayout" }
viewPager2 = { group = "androidx.viewpager2", name = "viewpager2", version.ref = "viewPager2" }
wear = { group = "androidx.wear", name = "wear", version.ref = "wear" }
watchface-core = { group = "androidx.wear.watchface", name = "watchface", version.ref = "watchface" }
watchface-complications = { group = "androidx.wear.watchface", name = "watchface-complications-rendering", version.ref = "watchface" }
workManager = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workManager" }

# Firebase
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics-ktx", version.ref = "firebaseAnalytics" }
firebase-crashlytics-ktx = { group = "com.google.firebase", name = "firebase-crashlytics-ktx", version.ref = "firebaseCrashlytics" }
firebase-crashlytics-gradle = { group = "com.google.firebase", name = "firebase-crashlytics-gradle", version.ref = "firebaseCrashlyticsGradle" }
firebase-perf-ktx = { group = "com.google.firebase", name = "firebase-perf-ktx", version.ref = "firebasePerf" }
firebase-perf-plugin = { group = "com.google.firebase", name = "perf-plugin", version.ref = "firebasePerfPlugin" }

# Google Play services
googleservices = { group = "com.google.gms", name = "google-services", version.ref = "googleServices" }
wearable-playservices = { group = "com.google.android.gms", name = "play-services-wearable", version.ref = "playServicesWearable" }
wearable-compile = { group = "com.google.android.wearable", name = "wearable", version.ref = "wearable" }
wearable-support = { group = "com.google.android.support", name = "wearable", version.ref = "wearable" }

# Jetbrains
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-playservices = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-play-services", version.ref = "coroutines" }
dokka = { group = "org.jetbrains.dokka", name = "dokka-gradle-plugin", version.ref = "dokka" }
kotlin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

# Other
coil = { group = "io.coil-kt", name = "coil", version.ref = "coil" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
okhttp-core = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-coroutines = { group = "ru.gildor.coroutines", name = "kotlin-coroutines-okhttp", version.ref = "okhttpCoroutines" }
retrofit-core = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit" }
subsampling = { group = "com.davemorrissey.labs", name = "subsampling-scale-image-view-androidx", version.ref = "subsampling" }
tasker = { group = "com.joaomgcd", name = "taskerpluginlibrary", version.ref = "tasker" }